create extension if not exists pgcrypto;
create table if not exists profiles (id uuid primary key references auth.users(id) on delete cascade, email text not null unique, created_at timestamptz not null default now());
create table if not exists pages (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, parent_id uuid references pages(id) on delete cascade, title text not null default 'Untitled', icon text, content jsonb default '{}'::jsonb, whiteboard jsonb default null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists page_images (id uuid primary key default gen_random_uuid(), page_id uuid not null references pages(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, path text not null, url text not null, created_at timestamptz not null default now());
alter table profiles enable row level security; alter table pages enable row level security; alter table page_images enable row level security;
create policy "profiles own" on profiles for all using (auth.uid()=id) with check (auth.uid()=id);
create policy "pages own" on pages for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "images own" on page_images for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types) values ('uploads','uploads',true,10485760,array['image/png','image/jpeg','image/webp','image/gif']) on conflict (id) do nothing;
create policy "upload own" on storage.objects for insert to authenticated with check (bucket_id='uploads' and owner=auth.uid());
create policy "read uploads" on storage.objects for select to authenticated using (bucket_id='uploads');
create policy "update own upload" on storage.objects for update to authenticated using (bucket_id='uploads' and owner=auth.uid());
create policy "delete own upload" on storage.objects for delete to authenticated using (bucket_id='uploads' and owner=auth.uid());
create or replace function public.handle_new_user() returns trigger as $$ begin insert into public.profiles (id,email) values (new.id,new.email); return new; end; $$ language plpgsql security definer;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
